version: '2'

services:
  database:
    image: mdillon/postgis
    container_name: sql_test_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=abc
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sql test

  web:
    image: sql test
    container_name: sql_test_app
    environment:
      - PG_PASSWORD=abc
      - PG_USER=postgres
      - PG_DBNAME=sql test
      - PG_PORT=5432
      - PG_HOST=database
      - AZURE_BLOB_CONTAINER=sql test
      - "AZURE_SAS_TOKEN="
    depends_on: 
      - "database"
    ports:
      - "6543:6543"
      - "8888:8888"
    tty: true
    volumes: 
      -  .:/sql test

  pgadmin:
    image: "thajeztah/pgadmin4"
    container_name: sql_test_pgadmin4
    ports:
      - "5050:5050"
