version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Log in to private registry
          command: |
            docker login \
            $CONTAINER_REGISTRY \
            -u $CONTAINER_REGISTRY_USERNAME \
            -p $CONTAINER_REGISTRY_PASSWORD

      - run:
          name: Build image
          command: | 
            docker build \
                --build-arg CONTAINER_REGISTRY=$CONTAINER_REGISTRY \
                -t sql test .

      - run:
          name: Start containers
          command: docker-compose up -d

      - run:
          name: Run tests
          command: |
            docker exec -it sql_test bash -c "python setup.py test"
            sudo mv htmlcov /tmp/artifacts

      - run:
          name: Build docs
          command: |
            docker exec -it sql_test bash -c "python setup.py docs"
            sudo mv docs/_build/html /tmp/artifacts/docs

      - run:
          name: Generate coverage badge
          command: |
            docker exec -it sql_test bash -c "coverage-badge -o coverage.svg"
            sudo mv coverage.svg /tmp/artifacts/

      - store_artifacts:
          path: /tmp/artifacts

      - run:
          name: Push image if commit is tagged
          command: |
            export TAG=$(git describe --tags --exact-match | grep "^v.*")
            if [ -z "$TAG" ]; then
                echo "no tag"
            else
                echo "tag = $TAG"
                docker tag sql test ${CONTAINER_REGISTRY}/sql test:${TAG}
                docker push $CONTAINER_REGISTRY/sql test:${TAG}
            fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: vanoord
          filters:
            tags:
              only: /.*/